version: "3.8"

services:
  backend:
    image: ${BACKEND_IMAGE} 
    ports:
      - "8080:8080"
    container_name: solar-backend
    depends_on:
      - frontend

  frontend:
    image: ${FRONTEND_IMAGE}  
    ports:
      - "3000:3000"
    container_name: solar-frontend
